In [1]:
import numpy as np

In [5]:
array_1d = np.array([1, 2, 3, 4])
print(array_1d)

[1 2 3 4]


In [8]:
type(array_1d)

numpy.ndarray

In [9]:
array_1d.ndim

1

In [11]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [12]:
type(arr_2d)

numpy.ndarray

In [13]:
arr_2d.ndim

2

In [14]:
arr_2d.size

6

In [15]:
arr_2d.shape

(2, 3)